repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.55.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - "@typescript-eslint/eslint-plugin@^6.11.0"
          - "eslint@^8.56.0"
          - "eslint-config-prettier@^9.0.0"
          - "eslint-plugin-prettier@^5.0.1"
          - "eslint-plugin-react@^7.33.2"
          - "eslint-plugin-react-hooks@^4.6.0"
