name: Deploy to development

on:
  push:
    branches-ignore:
      - main
      - dependabot/**

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: development
    secrets: inherit
